import { defineStore } from "pinia";

export const useFilterStore = defineStore('filter', {
    state: () => ({
        activeFilter: 'all',
        cards: [
            {
                id: 1,
                title: ' HDPE Water & Chemical Storage Drums 220L',
                category: 'INDUSTRIAL PLASTICS',
                image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJmDJj_e1OnXnQjMbdm77A5DZC5FOpmAwb6elqjL9SE4LB2g4nKvUkqrt6SG74G-xU_Dbpf9yXNfqEmNYqlysb6sSCnYrmnI1H__2ZhuoIRw1rAOpQL4hCfo7XagF9a5fX3c1_HUYx_7d9EQHdOG0_WZ7cJXmEhRJklBOv0y9X1o33iYYDF8eNai1blZhrgWQAe419anOkFiOn9CH3rPC5O17lL6yLE9J0fUcLqKC1j9I40NGEU7Hxog',
                description:'UN-certified blow molded high density polyethylene drum with airtight dual bung caps for liquid transport.',
                inStock: true,
                inBulk: true,
                price: 38000,
                unit: "drum",
                quantityRemaining: 160,
                unitPlural: "Drums",
                location: "Lagos"
            },
            {
                id: 2,
                title: ' Heavy-Duty Stainless Prep Table 1200mm',
                category: 'CATERING EQUIPMENT',
                image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDzF5X6gLcMmlYThj6uaznswam1psFVELklpBXjLJlu8X_MigjBfsKjNEGmBOnBWywi5hjaxyH9bntjhVSCUtWkAjVBb8nJF087KEqqHxR8dmwLQ4REKF4LL6n8VCryFmVJ-wqwTsLu4woQegZwKS6XBCuH5yKIFoR-oVrHrHXIAkkiWKOJyAb0DUNiHtSRNzYDj7GotQPEjA1J1EMQpJwsn1hXcKe2axuBGknBzFpvUjjN-f-FT2q0Ew',
                description:'Grade 304 food-service stainless steel worktop with adjustable galvanized undershelf and bullet feet.',
                inStock: true,
                price: 185000 ,
                unit: "unit",
                quantityRemaining: 45,
                unitPlural: "Units",
                location: "Ikeja",
                badge: 'Best Seller'
            },
            {
               id: 3,
                title: ' Industrial Safety Hard Hats with 6-Pt Harness',
                category: 'SAFETY EQUIPMENT',
                image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA1oqDsfIdJp_v-VX0EKP_ctRcFuLNaDVBWsyUNI1RddkEdb7AyP_HJHMwFf_nxbiqN1F1LrxMqvL8an7SfAr7Q18qK2Qdsdw5khopjH7rHMgbBxZQWt23-PiD2O0x4t4XMU9xQXZHtLM1B5Q4f5PAWzS0Vnj3JRyrkEZvInOh-QyI2u1hcxo-jzZtwYLD9qDJkd7EJn9eoKxofZdWp8ze_x_L6Vd3TpHQ7j1Jn-ofa4oXj-vWlFhRlUQ',
                description:'EN397 compliant impact-resistant ABS shell with 6-point suspension harness and ratchet size dial.',
                inStock: true,
                price: 12500 ,
                unit: "unit",
                quantityRemaining: 650,
                unitPlural: "Units",
                location: "Lagos",
                badge: null,
            },
            {
               id: 4,
                title: ' Industrial Pallet Stretch Film Rolls 500mm ',
                category: 'INDUSTRIAL PLASTICS',
                image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCLQ98ycUx7VqxubzMdas356Tyc4chG0HVKSRGszzOQw9FbPpslI0ImI2lMXAN3iwpK8wX65FvkiQEcnwJ6UWIxMOtGOgBrFxjAfGk5sneW23PUYi4vs0kR7UaSsJymgfC4KGafVHc_-Jns9z_UB4NlBOB3lt0dOsnbpxhX8lSc9ofNyyte4QDoEbQ_yZwTRI6Dsnax2Khv_xVUxICcNStN_1I7vZOUo9SBEOf9CVJBDyT9wbBcAJm3iA',
                description:'Cast co-extruded LLDPE pallet stretch film with superior puncture resistance and cling for warehouse logistics.',
                inStock: true,
                price: 14500 ,
                unit: 'roll',
                quantityRemaining: 650,
                unitPlural: 'Rolls',
                location: 'stock',
                badge: null,
            },
            {
               id: 5,
                title: ' Commercial Bain Marie 4-Pan Buffet Station ',
                category: 'CATERING EQUIPMENT',
                image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDfcNolEUisl7mvxeU-UyqWSo3b2lMqeruIj3M8QOmvOz7x1HKl4SHgFp0t1TwIZrmrhG68Vg-uAgfPKPVIRUvHB2RqHpDlJZZi70ARTG18LTGo25ESGp1O3ZFjISm8TvhEGoJcKSWMZTaBmPm05KiOlF1F_qK3f2enAf_vSkYc45E4pabmfJHnwIQl6DQ2rT5UHACU0VBnonBI8azSS6uTvDL43Dj67iefpnntuCj1IXBIxDL7VZE0GQ',
                description:'Electric wet-heat food warmer constructed from stainless steel with 4 deep 1/2 size pans and transparent lids.',
                inStock: true,
                price: 340000 ,
                unit: 'unit',
                quantityRemaining: 18,
                unitPlural: 'Units',
                location: 'Lagos',
                badge: 'WHOLESALE BULK',
            },
            {
                id: 6,
                title: ' High-Visibility Reflective Safety Vests (Pack of 10) ',
                category: 'SAFETY EQUIPMENT',
                image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBfGfjAI3pdtfAnPLzdkno4Jsci2hWjQcwM9tIa7odn-6eauMyMMUHceu12Fe8lxoVoi6ii1cA3PZYM1ZXvWI3rr2qpytb03ofZ2KN0WWrEFNj5_Edt0KnUOg3BXF8RA7Urh4ITnDHxHeyoXrAnelG7FFjIiGY2lClM8012MJxm1O11MgjaUIBdotH8GlWZfB0VUx2KCEQnmRVpPgHcrTbDxLj_L8l-5ajdGO5253tZOTOA9d9nMZl7Iw',
                description:'Electric wet-heat food warmer constructed from stainless steel with 4 deep 1/2 size pans and transparent lids.',
                inStock: true,
                price: 340000 ,
                unit: 'unit',
                quantityRemaining: 18,
                unitPlural: 'Units',
                location: 'Lagos',
                badge: 'WHOLESALE BULK',
            },
        ]
    })
})